# Generated by Django 5.2.4 on 2025-07-22 05:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stock', '0002_alter_werehouse_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(help_text='The category code consists of 3 numbers and one English letter. Example: 526f, 392b', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}[a-z]{1}')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, help_text='A barcode consists of 13-16 digits.', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(16), django.core.validators.RegexValidator('^\\d+')]),
        ),
        migrations.CreateModel(
            name='WerehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_werehouse', to='products.product')),
                ('werehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_products', to='stock.werehouse')),
            ],
        ),
    ]
